### ISSUE TITLE
Training on original input

### ISSUE THREAD

**Issue by BsmKdd** [ika-rwth-aachen/Cam2BEV#27]
Hello!

I want to train the model (uNetXST) on the original images as input. I was wondering what change needs to be done in that case? 

I assume I will have to change `train.py` so that no one-hot-encoding is done on the input? In that case, what will the value of `n_classes_input` be? Just the channels of the image (3)?

**Comment by lreiher** [comment]
By "original images", do you mean ...
1. the original, non-semantically-segmented camera images?
2. or the semantically-segmented images in RGB format instead of one-hot encoding?
---
1. The datasets that we have released only contain the semantically segmented images. If you happen to have another dataset with real camera images, simply follow the same steps as outlined in 2.
2. If you would like to input the semantically-segmented images as RGB images instead of one-hot encoded tensors, you need to make minor code changes in the training script:
   - set `n_classes_input = 3`
   - remove the one-hot encoding [`inp = utils.one_hot_encode_image_op(inp, conf.one_hot_palette_input)`](https://github.com/ika-rwth-aachen/Cam2BEV/blob/master/model/train.py#L115)
   - optionally cast the input images from int to float
   - optionally normalize the float inputs from `[0, 255]` to `[0, 1]` or `[-1, 1]`
   - same changes would need to be made to `evaluate.py` and `predict.py`

Does this answer your question?

**Comment by BsmKdd** [comment]
Yes, that's perfect.

 Thank you for the detailed instructions!
