### ISSUE TITLE
Performance when evaluating custom data

### ISSUE THREAD

**Issue by aqx95** [ika-rwth-aachen/Cam2BEV#29]
Firstly i would like to thank you very much for this repository and the ideas introduce in the paper. I have reproduce the results using 1_FRLR deeplab_mobilenet and the provided dataset and was looking to test on some images that we have collected on my side.
What i found is that using the trained model, i wasn't able to interpret the results using my own images (We mount the fisheye camera on a truck and run segmentation and our own ipm to generated the homography image as input)

Below are the input and result from our custom image
Input:
![0_rotate_orig (copy)](https://user-images.githubusercontent.com/39089009/180122397-0ec6c2af-1d33-494c-aff8-4eac0d4130f8.png)
Result: 
![0_rotate](https://user-images.githubusercontent.com/39089009/180121981-16f8967e-b7a4-4927-bd2b-035b1e2bff08.png)

Result using 1_FRLR validation data provided
Input:
![v_0_0411000 (copy)](https://user-images.githubusercontent.com/39089009/180123049-133c5452-a8f5-4a97-a0c5-13e01a7d75bc.png)
Result:
![v_0_0411000](https://user-images.githubusercontent.com/39089009/180123123-64047f8e-7496-4212-84fc-9066ed24746d.png)

I am not sure why there is such a huge difference in the results. Although I was expecting a poorer result because of changes in the data domain, i wasn't expecting instances like cars, which was represented in our own homography, to disappear upon inference.

I was wondering if there is anything that i did wrongly during the predict step and i look forward to anyone who could shed a light on whether its a prediction step issue or its a model generalization issue

Thank you

**Comment by lreiher** [comment]
Thanks for your interest!

Here are a couple of things we have noticed:
- The validation result you have attached doesn't even show the ego vehicle, which is a little surprising, since it's included in all training samples at exactly the same location. You can also see it being predicted in the results shown in our paper. Perhaps something is wrong with the training of the model already.
- Some problems due to the domain shift are probably expected, as you also pointed out. Not only are you using real-world data, but also fisheye cameras and a truck. The truck perspective for example allows to see over cars, resulting in far less distortion in the IPM image.

To further analyze this, could you please post the config file that you were using to train and predict?
