### ISSUE TITLE
OOM Issue on UNetXST -- Occupies 55GB of physical RAM

### ISSUE THREAD

**Issue by ogkdmr** [ika-rwth-aachen/Cam2BEV#6]
Hello @lreiher, thank you for the fabulous work!

 We're trying to reproduce your results on the UNetXST model with your dataset and your configuration (config.1_FRLR.unetxst.yml ). I can confirm a previous issue that the RAM usage continuously and rapidly grows as soon as the training starts. I am talking about the main RAM, not the GPU RAM. By the time process is killed due to OOM, it occupies ~55GB of physical memory. We're trying to train on two RTX 3090s with 24GB RAM each.  

Can you think of a part of your code where stuff accumulates in memory without being garbage collected? It's very strange that you haven't encountered this. As a note, we were able to train MobileNetV2 with your 1.FRLR configuration so this issue is endemic to UNetXST.

**Comment by bastilam** [comment]
Hello @ogkdmr, 

I just did a clean install and download of the data. Cam2BEV did not work with my GPU out of the box because tensorflow 2.1 from the requirements.txt in this project does not work with the newer cuda version which I had already installed on my PC. The training only used my CPU and a lot of RAM.

I just installed tensorflow 2.4 using `pip install tensorflow==2.4` inside my conda environment. Now, the training uses my GPU and it also uses a lot less RAM.

Maybe this is something you could try as well. Make sure the training actually uses the GPU.

Watch out for errors of this kind: `Could not load dynamic library 'libcudnn.so.7'`

In another terminal tab, you can watch whether your GPU memory is actually used with `watch nvidia-smi`

**Comment by ogkdmr** [comment]
Thank you @bastilam for taking the time of reproduce the issue. I can confirm that the model is training on the GPU. Perhaps we need to get more RAM for our machine, although we already have around 128GB.

You can close the issue for now. I will keep you updated if I resolve the issue.
